# Generated by Django 4.0.3 on 2022-03-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
